name: run-puzzles

on:
  workflow_dispatch:
  push:

jobs:
  job:
    name: puzzle-runner
    runs-on: ubuntu-latest
    env:
      SESSION: "${{ secrets.SESSION_ID }}"
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun index.ts
